version: '2'

services:
  cassandra_1:
    build: cassandra-config
    ports:
      - "8888:8888"
      - "9042:9042"
      - "9160:9160"
      - "7199:7199"
    expose:
      - "7000"
      - "7001"

  cassandra_2:
    build: cassandra-config
    expose:
      - "9042"
      - "9160"
      - "7000"
      - "7001"
      - "7199"


