FROM ubuntu:15.10
MAINTAINER Daniel Somerfield <dsomerfi@thoughtworks.com>

RUN apt-get -y update && apt-get install -y openjdk-8-jdk && apt-get install -y vim && apt-get -y install curl && apt-get -y install dnsutils
RUN apt-get -y install dnsutils